from flask import Blueprint, render_template_string, request, session, redirect, url_for, flash
from werkzeug.security import check_password_hash, generate_password_hash
from config import get_db
import json

login_bp = Blueprint('login', __name__)

@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    if session.get('user_id'):
        return redirect(url_for('index.index'))
        
    error = None
    
    if request.method == 'POST':
        user = request.form.get('username')
        passwd = request.form.get('password')
        
        conn = get_db()
        if conn:
            cursor = conn.cursor(dictionary=True)
            cursor.execute("SELECT * FROM users WHERE username = %s AND is_active = 1", (user,))
            row = cursor.fetchone()
            
            if row:
                verified = False
                
                # In PHP: password_verify(pass, hash) checks against bcrypt/argon2
                # In Python: check_password_hash checks against pbkdf2 or bcrypt (if generated by werkzeug)
                # However, PHP's password_hash usually generates a $2y$ string. Werkzeug might not natively understand it unless we use passlib or bcrypt module.
                # Assuming simple check for now, can import `bcrypt` if this fails.
                
                try:
                    if check_password_hash(row['password_hash'], passwd):
                        verified = True
                except ValueError:
                    # In case of incompatible hash formats
                    import bcrypt
                    if row['password_hash'].startswith('$2y$'):
                        # Python bcrypt expects $2b$ instead of $2y$
                        compatible_hash = row['password_hash'].replace('$2y$', '$2b$', 1).encode('utf-8')
                        if bcrypt.checkpw(passwd.encode('utf-8'), compatible_hash):
                            verified = True

                # Legacy Plain Text (Migration)
                if not verified and passwd == row['password_hash']:
                    verified = True
                    new_hash = generate_password_hash(passwd)
                    cursor.execute("UPDATE users SET password_hash=%s WHERE user_id=%s", (new_hash, row['user_id']))
                    conn.commit()
                
                if verified:
                    session['user_id'] = row['user_id']
                    session['role'] = row['role']
                    session['full_name'] = row['full_name_ar']
                    
                    try:
                        perms = json.loads(row['permissions']) if row['permissions'] else []
                    except json.JSONDecodeError:
                        perms = []
                    
                    if not isinstance(perms, list):
                        perms = []
                        
                    session['permissions'] = perms
                    conn.close()
                    return redirect(url_for('index.index'))
                else:
                    error = "كلمة المرور غير صحيحة"
            else:
                error = "اسم المستخدم غير موجود"
            conn.close()

    html = """
    <!DOCTYPE html>
    <html lang="ar" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HealthPro OS - Login</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.rtl.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='apple_ui.css') }}">
        <style>
            body {
                height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                padding: 0;
                overflow: hidden;
            }
            .login-box {
                width: 400px;
                animation: fadeInScale 0.6s ease-out;
            }
            @keyframes fadeInScale {
                from { opacity: 0; transform: scale(0.95); }
                to { opacity: 1; transform: scale(1); }
            }
        </style>
    </head>
    <body>
        <div class="login-box">
            <div class="apple-card shadow-lg py-5 px-4">
                <div class="mb-4 text-center">
                    <i class="fas fa-hand-holding-medical text-primary fa-4x mb-3"></i>
                    <h2 class="fw-bold">HealthPro <span class="text-primary">OS</span></h2>
                    <p class="text-muted small">سجل الدخول للمتابعة</p>
                </div>
                
                {% if error %}
                    <div class="alert bg-danger-subtle text-danger border-0 small mb-4 rounded-4 text-center">
                        <i class="fas fa-exclamation-triangle me-1"></i> {{ error }}
                    </div>
                {% endif %}
                
                <form method="POST">
                    <div class="mb-3 text-start">
                        <label class="form-label ms-2 small fw-bold">اسم المستخدم</label>
                        <input type="text" name="username" class="form-control form-control-apple" placeholder="Username" required autofocus>
                    </div>
                    <div class="mb-4 text-start">
                        <label class="form-label ms-2 small fw-bold">كلمة المرور</label>
                        <input type="password" name="password" class="form-control form-control-apple" placeholder="••••••••" required>
                    </div>
                    <div class="d-grid mt-4">
                        <button type="submit" class="btn btn-primary py-3 fs-5 rounded-pill shadow">دخول النظام <i class="fas fa-chevron-left ms-2"></i></button>
                    </div>
                </form>
                
                <div class="mt-5 text-center text-muted small" style="letter-spacing: 1px;">
                    APPLE SYSTEM v5.0 SECURED
                </div>
            </div>
        </div>
    </body>
    </html>
    """
    return render_template_string(html, error=error)
